import { useEffect, useState } from "react";
import { db } from "../../config/firebase";
import Header from "../../components/Header";
import Chatlist from "../../components/Chatlist";
import Head from "next/head";

function Chat() {
  const [people, setPeople] = useState([]);

  useEffect(() => {
    db.collection("users").onSnapshot((snapshot) =>
      setPeople(
        snapshot.docs.map((doc) => ({
          id: doc.id,
          data: doc.data(),
        }))
      )
    );
  }, []);
  return (
    <>
      <Header />
      <div>
        <Head>
          <title>Chat list</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          {people.map((people) => (
            <Chatlist
              key={people.id}
              id={people.id}
              username={people.data.username}
              photoURL={people.data.photoURL}
            />
          ))}
        </main>
      </div>
    </>
  );
}

export default Chat;
